src/components/Team/members/change-role.tsx
=> Fixed #124

src/components/Team/members/index.tsx
=> Issue #147

.env.development.sample, package-lock.json, package.json, src/api/custom-fetch.ts, src/api/geosearch/list.ts, src/api/geosearch/mock.ts, src/auth/container.tsx, src/components/Data/GIS.tsx, src/components/Data/GISs.tsx, src/components/Data/fields.tsx, src/components/Data/map-container.tsx, src/components/Data/publish.tsx, src/components/Data/text-editor.tsx, src/components/Data/upload.tsx, src/components/custom/GeoloniaMap.tsx, src/lib/merge-geojson.ts, src/lib/read-file.ts, src/redux/actions/geosearch.ts, src/redux/store.ts, src/types/index.ts
- Enable to store geoJSON state (currently, work with mocked API request)
- visualize geoJSON
- GeoJSON previewer in a textarea (currently, No CSS)
=> geosearch state

src/components/Data/fields.tsx, src/components/Maps/APIKey.tsx, src/components/custom/Delete.tsx
This is a patch for `<Delete />`  component and its usage Optimized props and enhancement for translation.
close #151
=> Enhance delete component

src/components/Data/GISs.tsx, src/components/Data/fields.tsx, src/components/Maps/APIKey.tsx, src/components/Maps/APIKeys.tsx, src/components/Team/members/invite.tsx, src/components/custom/AddNew.tsx, src/components/custom/Delete.tsx
- Disable buttons on request
- type enhancement
=> Enhancement for `<AddNew />` component

src/components/Maps/APIKey.tsx
=> Enhance usability for APIKey page

src/components/Data/GISs.tsx, src/components/Data/fields.tsx, src/components/Maps/APIKey.tsx, src/components/Maps/APIKeys.tsx, src/components/Team/members/invite.tsx, src/components/custom/AddNew.tsx, src/components/custom/Delete.tsx, src/components/custom/Table.tsx
=> Enable pagenation

src/components/Dashboard.scss, src/components/Dashboard.tsx
=> Issue #172

src/auth/container.tsx, src/components/Data/upload.tsx, src/components/ForgotPassword.tsx, src/components/ResetPassword.tsx, src/components/Signin.tsx, src/components/Signup.tsx, src/components/User/security.tsx, src/components/verify.tsx
This patch enhances error handling and fixes #170 !
=> Bugfix/validation and error check/issue 170

src/components/Data/GISs.tsx, src/components/Maps/APIKeys.tsx, src/redux/actions/map-key.test.ts, src/redux/actions/map-key.ts
This patch sorts map key with `createAt` parameter.
close #153
=> Sort map keys

src/components/custom/Save.tsx
- we can press after request success/failed
- message snackbar will disappear in a few certain seconds
close #137
=> Enhance <Save /> component

src/api/geosearch/list.ts, src/api/geosearch/mock.ts, src/api/keys/create.ts, src/api/keys/list.ts, src/auth/container.tsx, src/components/Data/GISs.tsx, src/components/Maps/APIKeys.tsx, src/components/custom/Table.tsx, src/lib/by-create-at.ts, src/lib/date-parse.test.ts, src/lib/date-parse.ts, src/redux/actions/geosearch.ts, src/redux/actions/map-key.test.ts, src/redux/actions/map-key.ts, src/types/index.ts
Use Moment object and apply timezone when serialize.
Fix #130
=> Feature/timezone localization/issue 130

package.json, src/lang/ja.json
This patch make it easier to read the diff of langage.json.
=> Format when language.json is generated

src/api/geosearch/mock.ts, src/auth/container.tsx, src/components/Data/GIS.tsx, src/components/Data/GISs.tsx, src/components/Maps/APIKey.tsx, src/components/Maps/APIKeys.tsx, src/components/Navigator.tsx, src/components/Team/Billing.tsx, src/components/Team/general/fields.tsx, src/components/Team/general/index.tsx, src/components/Team/members/change-role.tsx, src/components/Team/members/index.tsx, src/components/User/profile.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/lib/date-parse.ts, src/redux/actions/user-meta.ts
このパッチは、billing email の一貫性を向上させるためのものです。
Owner 権限のユーザーのメールアドレスだけが billing email として登録されるようにしています。
=> Enhancement/team creation and email/issue 178

src/components/Maps/APIKey.tsx, src/components/Maps/APIKeys.tsx, src/components/ResetPassword.tsx, src/components/Signin.tsx, src/components/Signup.tsx, src/components/verify.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
地図を表示する際のCSSの例をステップガイドに追加しました。
=> Add css guide to display map

src/components/Navigator.tsx
This patch refreshes the state on team creation and reduces inconsistency.
close #191
=> Reload when team successfully created

src/lang/ja.json, src/lang/ja.po
=> Add some translation

src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
参考:
https://ayatakesi.github.io/gettext/0.18.3/html/Fuzzy-Entries.html
=> Fixed fuzzy

src/components/ForgotPassword.scss, src/components/ResetPassword.scss, src/components/Signin.scss, src/components/Signup.scss
=> Fix margin

src/components/Signup.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Add notation

src/components/Maps/APIKey.tsx
=> Fix code box style

src/components/Team/members/invite.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Prevent invite a member they are already a member of the team

src/components/ForgotPassword.tsx
=> Disable send button if no valid username or email specified

src/components/Maps/APIKey.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Improve ux to get html

package-lock.json, package.json, src/components/Maps/APIKey.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> ウェブサイトに地図を追加するためのUIを改善

src/components/ForgotPassword.tsx, src/components/ResetPassword.tsx, src/components/Signin.tsx, src/components/Signup.tsx
Use better HTML for the forms. This is also responsible for 1password detection.
close #192
=> Form the forms as it is

src/components/Team/members/change-role.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Add details on the roles

package-lock.json, package.json
This reverts commit 38861a96628a34675afe8f6352bd03aa2b9f9f64.
Fixed: #264
=> Revert "update deps"

src/components/ForgotPassword.tsx, src/components/ResetPassword.tsx, src/components/Signin.tsx, src/components/Signup.tsx
Reverts geolonia/app.geolonia.com#266
=> Revert "1password detection"

src/components/ForgotPassword.tsx, src/components/ResetPassword.tsx, src/components/Signin.tsx, src/components/Signup.tsx, src/components/verify.tsx
to be wrapped with `<form />` to enable 1password auto-detection and improve semantics.
=> Fix the forms

src/components/Team/members/change-role.tsx, src/lang/ja.po, src/lang/lang.pot
=> Add member privilages description

src/components/ForgotPassword.tsx, src/components/ResetPassword.tsx, src/components/Signin.tsx, src/components/Signup.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
`button[type=sumbit]` を #192 で足しましたが意図しない遷移が発生するので `MouseEvent.preventDefault()` を追加しました。
Related with #192, #271
=> Master  fix on auth handler page transition

package-lock.json, package.json, src/auth/container.tsx, src/components/ForgotPassword.tsx, src/components/ResetPassword.tsx, src/components/Signin.tsx, src/components/Signup.tsx, src/components/custom/languages.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/lib/estimate-language.ts
=> Signup page should be with language switcher

src/components/Signup.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/lib/cognito/parse-error.ts, src/lib/validators.test.ts, src/lib/validators.ts
=> Add cognito error handling when sign up

src/components/Signin.tsx, src/components/Signup.tsx, src/components/custom/status-indication.tsx, src/components/verify.tsx, src/constants.ts
以下のページ遷移が壊れているのを直しました。
1. サインアップ画面
2. 検証コード入力画面
3. サインイン画面
=> Fix page transiton when sign up

src/components/verify.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
こちらは検証コード入力ページの改修です。以下を行っています。
- エラーハンドリング追加
- フォームのユーザビリティ改善
=> Fix verification page error handling and userbility

src/auth/index.ts, src/components/ForgotPassword.tsx, src/components/ResetPassword.tsx, src/components/Signin.tsx, src/components/Signup.tsx, src/components/verify.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/lib/cognito/parse-error.ts
パスワードをリセットする時のページ遷移などが壊れているのを直しました。
=> Fix page transiton when reset password

src/auth/index.ts, src/components/Paperbase.tsx, src/components/ResetPassword.tsx, src/components/custom/Alert.tsx, src/components/resend-code.tsx, src/components/route-controller.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/lib/cognito/parse-error.ts
アカウントの検証をせずに放置したユーザーが、後から再度検証コードを要求するフォームを追加。
=> Add resend confirmation code process

src/auth/container.tsx, src/components/Data/GeoJsons.tsx, src/components/custom/AddNew.tsx
done:
- This patch replaces endpoints with that of Elasticsearch
not done:
- Paginated API request
=> Replace GeoJSON API endpoint

src/components/Data/GeoJsons.tsx, src/components/custom/AsyncTable.tsx
=> Add GeoJSON pagenation which follows pagenated API request

src/components/Data/GeoJson.tsx, src/components/Data/GeoJsons.tsx, src/components/Data/MapEditor.tsx
=> Enable Feature Requests

src/components/Data/GeoJson.scss, src/components/Data/GeoJson.tsx, src/components/Data/MapEditor.tsx, src/types/index.ts
Add WebSocket Client and notify if update required.
=> WebSocket client

src/components/Team/Billing.tsx, src/components/Team/general/fields.tsx, src/components/Team/members/change-role.tsx
- クレジットカード登録フォームは owner 以外には表示されないように変更 (API は元から 403 が返る)
- チームの　billingEmail が member 権限でも enabled な状態だったので member なら disabled に変更 (API は元から 403 が返る)
=> Payment display control

src/components/custom/Save.tsx
ローディングアニメーションの色が背景色とかぶっていたので変更しました。
=> Enhance loading animation color

src/auth/index.ts, src/components/AcceptInvitation.tsx, src/components/Header.tsx, src/components/Paperbase.tsx, src/components/Team/members/invite.tsx, src/components/custom/AddNew.tsx, src/components/route-controller.tsx
メンバー招待用のリンク（メールに記載して送信するもの）をクリックした時のページを追加しました。
=> Member invitation

src/components/Data/PropsEditor.tsx
別のフィーチャを選択したときにtitleとdescriptionの値が変わらないのを修正
=> Props エディタのバグ修正

src/components/Data/GeoJsons.tsx
=> GeoJSON API のリスト画面にローダーを追加

src/components/Data/GeoJsonMeta.tsx
- state 管理の一貫性向上
- ワーニングを抑制
close #334
=> ダウンロード用のURLコピーの input に readonly 属性を付与

src/components/Data/GeoJson.tsx, src/components/Data/MapEditor.tsx, src/components/custom/GeoloniaMap.tsx
=> Add Cognito JWT to customtiles requests

.env.development.sample, netlify.toml, src/components/Data/GeoJson.tsx, src/components/Data/GeoJson/hooks/use-geojson.ts, src/components/Data/GeoJsonMeta.tsx, src/components/Data/ImportDropZone.tsx, src/components/Data/ImportDropZoneButton.tsx, src/components/Data/MapEditor.tsx, src/components/custom/GeoloniaMap.tsx
=> Don't clear gvp_status when updating GeoJSON meta

netlify.toml, package.json, src/index.tsx, yarn.lock
=> Add Sentry

src/components/custom/AddNew.tsx
Enter キーの他にボタンのクリックも拾えるようにしました。
follows #374
=> Submit には </Button> も含める

.env.development, .env.development.local.sample, .env.development.sample, .gitignore
.env.development と .env.dvelopment.local の活用、前者はGeolonia関連のリソース、後者は社外のリソースという使い分け？
@keichan34 こんな感じで大丈夫でしょうか？
=> 環境変数の管理の改善

src/components/Data/GeoJsons.tsx
DynamoDB側のページネーションに合わせるまで一旦すべてを読み込むように
Closes #373
=> Use Table instead of AsyncTable temporarily

src/components/Data/ImportDropZone.tsx, src/components/Data/ImportDropZoneButton.tsx
=> GeoJSONを再アップロード時に上書きされる説明を追加

src/components/Data/GeoJson.tsx, src/components/Data/GeoJsonMeta.tsx, src/components/Data/ImportDropZone.tsx, src/components/Data/MapEditor.tsx, src/components/Data/StyleSelector.tsx, src/components/custom/GeoloniaMap.tsx
APIサポートは https://github.com/geolonia/api.geolonia.com/pull/182 で管理
geolonia/geojson-vector-pipeline#13
=> Allow CSV files to be uploaded

src/components/Data/GeoJson.tsx, src/components/Data/ImportDropZone.tsx, src/components/Data/ImportDropZoneButton.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/lib/sleep.ts, src/sleep.ts
=> GVP の処理をプログレスバーで視覚的に表示

src/components/ResetPassword.tsx, src/lib/cognito/parse-error.ts
パスワードリセットの際のエラーメッセージを適切に表示するようにしました。
close #341
=> パスワードリセットの際の表示バグの対応

src/components/Data/GeoJsonMeta.tsx
=> get-geolonia の新機能でコードスニペットをシンプルに

src/components/Navigator.tsx, src/global.d.ts
=> Hide Location Data menu behind feature flag

src/components/Team/general/fields.tsx
=> チームの URL と概要を非表示に

src/components/Team/members/invite.tsx, src/components/custom/AddNew.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Message before inviting a user

src/App.scss, src/App.tsx, src/components/CommonNotification.tsx, src/components/Maps/APIKeys.tsx, src/components/Paperbase.tsx, src/components/custom/AddNew2.tsx, src/contexts/notification.ts, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> API キー作成時にダイアログを飛ばして連番の名前で作成する

src/components/Navigator.tsx
Closes #451 
サイドバーのテキストを以下に変更。翻訳はコンフリクトしそうなのでマージ後にPRを送ろうと思います…！
```
- 地図
- API キーの管理
```
=> サイドバーのテキストを修正

src/components/Navigator.tsx
位置情報データが表示するときに react key=地図 が重複するエラーが出るため、同じセクションに統合しました
=> Merge map sections in sidebar

src/components/Maps/APIKey.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> APIキーの設定ページのレイアウト変更（2カラム版）

src/components/Team/Billing.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Add credit balance

src/components/Team/Billing.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Add map view count. Total count for this month for now.

src/components/Tutorials.tsx
=> CardActionArea>Button のワーニングを除去

src/assets/mui-theme.ts, src/components/Data/GeoJson.tsx, src/components/Data/GeoJsonImporter.tsx, src/components/Data/GeoJsonMeta.tsx, src/components/Data/ImportDropZone.tsx, src/components/Data/ImportDropZoneButton.tsx, src/components/Paperbase.tsx, src/components/Team/general/delete.tsx, src/components/Team/members/index.tsx, src/components/custom/AddNew.tsx, src/components/custom/Delete.tsx, src/components/custom/status-indication.tsx, src/constants.ts, src/global.d.ts, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
* isPaidTeam 周りの制限を外す
* Geolonia Proの文言を調整
geolonia/tasks-dev#51
=> Geolonia Pro 調整

src/components/Data/GeoJson.tsx, src/components/Data/GeoJson/hooks/use-metadata.ts, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/lib/fetch.ts
- Prevent map display with mbtiles direct upload
- I18nize
close #539
=> MBTiles アップロード時に Simple Style のレイヤーがなければ地図を表示しない

src/components/Team/Billing.tsx
Related to geolonia/tasks-dev#57
無料プラン中に使用グラフを正しく表示させる
期間も表示する
=> Free plan usage details

src/components/Navigator.tsx, src/components/Router.tsx
=> Hide location data

src/components/Signin.tsx, src/components/Signup.tsx, src/components/verify.tsx, src/hooks/invitation-token.ts
今まではサインアップの後でチームの招待を承諾していましたが、これをメールアドレス認証（`/verify`）の方に持ってきました。
=> チーム加入の処理はメールアドレス認証後に行う

src/components/Navigator.tsx, src/components/Team/general/fields.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Make billing e-mail address editable by user

src/components/Team/general/fields.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Fix label for team name setting

src/components/Navigator.tsx
=> Mark current navigation location

src/components/Team/members/index.tsx, src/components/Team/members/suspend.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> 一時停止を解除のメニューを追加

src/assets/mui-theme.ts, src/components/Team/members/index.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
自分からチームを離脱できるように修正。
close #204 
ツールチップの色の関係から、 #578 に依存。
=> 自分自身をチームから削除可能にする

src/components/User/avatar.tsx
ユーザーアバターのアップロードが壊れていたので直しました :bow:
=> Fix avatar upload

src/auth/container.tsx, src/components/Dashboard.tsx, src/components/Header.tsx, src/components/Signin.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/redux/hooks.ts
* ユーザーの名前をプロフィールメニューの隣に表示する(もうちょっと気づきやすくするため？)
* ユーザーログイン時に問題があったらエラーが表示されなかったバグを修正
* AuthContainerを functional component に書き換え
=> UI improvements

src/components/Data/GeoJsonMeta.tsx, src/components/Maps/APIKey.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
=> Emphasize before <body /> notation

src/components/Team/Billing/usage-chart.tsx
React Chart JS は別のオブジェクトを data プロパティとして受け取るとデータの内容が同じであってもグラフを再レンダーする。このページでは data は更新されることはないため、data を最初に受け取った時だけ更新するようにしている。
=> チャートの再レンダーを防ぐ

package.json, src/components/Paperbase.tsx, src/components/Team/Billing.tsx, src/global.d.ts, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, yarn.lock
requires geolonia/api.app.geolonia.com#219
=> Improvements

src/auth/container.tsx, src/components/LoadingScreen.tsx, src/components/Navigator.tsx, src/components/Paperbase.tsx, src/hooks/session.ts, src/redux/hooks.ts
Also shows loading spinner when initializing authentication
=> Force sign-out if refresh session failed

src/components/User/User.tsx, src/components/User/personal-access-token.tsx, src/components/User/profile.tsx, src/components/User/security.tsx, src/components/User/user.scss, src/global.d.ts, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/redux/actions/user-meta.ts, src/redux/apis/app-api.ts
=> パーソナルアクセストークンの発行 UI

package.json, src/components/Data/GeoJson.tsx, src/components/Data/GeoJsonImporter.tsx, src/components/Data/ImportDropZone.tsx, src/components/Data/ImportDropZoneButton.tsx, src/constants.ts, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/redux/apis/api.ts, yarn.lock
- 複数のファイルの場合はシェープファイルとして処理する。必須の3つのファイル(shp, shx, dbf)がない場合はエラーにする
- 1つだけのファイルの場合は geojson/csv/mbtiles として処理
=> Enable shapefile upload

src/components/Team/Billing.tsx, src/components/Team/Billing/usage-chart.tsx, src/redux/apis/app-api.ts, src/redux/hooks.ts
* Add UI to query prev/next month usage
=> Deploy production

src/components/Team/Billing/usage-chart.tsx
=> Usage chart bug fix (#688)

src/components/Team/Billing.scss, src/components/Team/Billing/usage-chart.tsx, src/components/custom/date-picker.tsx, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot
- Date Range selector
- HTML ダウンロード （Blob URL 作成して、別ページで表示）
- CSV ダウンロード（ダウンロード）
=> calendar range picker with usage

src/components/Team/Billing.tsx, src/components/Team/Billing/payment-history.tsx, src/global.d.ts, src/lang/ja.json, src/lang/ja.po, src/lang/lang.pot, src/redux/hooks.ts
* Fix typo Recipient
* Show billing even if Operator
* サブスクリプションがある場合は従量課金になるため、「地図表示回数が上限に達したため〜」を表示しない
* Display Refunded
Co-authored-by: Keitaroh Kobayashi <keita@kbys.me>
=> Deploy production お支払いページのバグ修正・改修 (#698)

src/components/Team/Billing/usage-chart.tsx
=> 地図表示回数の3桁区切り表示

src/components/Team/Billing/usage-chart.tsx
* Use locale number string for key usage count
=> Deploy production 地図表示回数の3桁区切り表示 (#710)
