src/auth/index.ts
src/components/verify.tsx

This patch make the dashboard to send browser language when signup and store it as initial language value.
The initial language value will be used i18nization of email.
```shell
$ AWS_DEFAULT_REGION=us-east-1 aws cognito-idp admin-get-user --user-pool-id=us-east-1_0C5yMqsfC --username=ryo102
{
"Username": "ryo102",
"Enabled": true,
"UserStatus": "UNCONFIRMED",
"UserCreateDate": 1580461505.231,
"UserAttributes": [
{
"Name": "sub",
"Value": "xxxx"
},
{
"Name": "email_verified",
"Value": "false"
},
{
"Name": "locale",
"Value": "ja"
},
{
"Name": "email",
"Value": "ryo+102@geolonia.com"
}
],
"UserLastModifiedDate": 1580461505.231
}
```

Send default language as locale attribute

---

src/components/Maps/APIKey.tsx
src/lib/normalize-origin.test.ts
src/lib/normalize-origin.ts

Canonicalize origin.
`https://example.com/` should be canonicalized as `https://example.com`.

Add Origin normalizer

---

src/components/custom/Table.tsx

`inputProps["aria-label"]: string` is just an accessibility attribute and no actual visible label texts have not specified 😅
close #242

Show label row per page

---

src/components/Maps/APIKey.tsx

以前新しく導入した主キー `keyId` への置換漏れがあり、API キーが削除できなかったのでこれを修正しました。

Fix key deletion

---

src/auth/index.ts
src/components/ForgotPassword.tsx
src/lang/ja.json
src/lang/ja.po
src/lang/lang.pot

パスワード紛失フォームのエラーハンドリングとメッセージの追加です。

Add error handling and message display for password reset page

---

src/components/Data/GeoJsonMeta.tsx

サーバー側では 404 を返すように対応
https://github.com/geolonia/api.geolonia.com/pull/121

ダウンロードボタンはドラフト状態の時は不活化

---

src/components/Data/GeoJson.tsx
src/components/Data/MapEditor.tsx

新しい Props を与えた時に、 Mapbox Draw の `draw.create` などのイベントハンドラが更新される必要があったので、その Effect を追加しました。

Mapbox Draw のイベントハンドラがレンダー時に置き換えるように修正

---

package-lock.json
src/auth/container.tsx
src/components/Data/GeoJson.tsx
src/components/Data/GeoJsonMeta.tsx
src/components/Team/Billing.tsx
src/components/Team/plan-modal.tsx
src/lang/ja.json
src/lang/ja.po
src/lang/lang.pot

- File API 経由でダウンロードするボタンの追加
- URL をコピー可能に変更
- プライベートなエンドポイントは一旦削除

GeoJSON の公開エンドポイントに関する UI の修正

---

src/auth/container.tsx
src/auth/index.ts
src/components/DeveloperBlog.tsx
src/components/Signin.tsx
src/components/custom/languages.tsx
src/lib/estimate-language.ts
src/redux/middlewares/local-storage.ts

~明示的に言語を選択する UI を以前追加していたため、それに追従しました。~
~サインアップ後のデフォルトのダッシュボードの表示言語は、サインアップ時に表示していた画面の言語になります。~

サインイン・サインアップ時の言語のハンドリング

---

src/auth/container.tsx
src/auth/index.ts
src/components/Signup.tsx
src/lib/estimate-language.ts

#314 でサインアップした画面の言語設定と別の言語設定を送ってしまうケースがあったので修正しました。
サインインしていない時、言語設定はURL とlocalStorage の場所で保存されうるのですが、そこから言語設定を取得する際の優先順位を固定しました。

サインアップ時の言語のハンドリングの堅牢化

---

src/components/resend-code.tsx
src/lang/ja.json
src/lang/ja.po

サインインに失敗した直後など、推定できる時はユーザー名を自動で埋めるようにしました。

コードを再送するUIのユーザービリティ改善

---

src/components/Maps/APIKey.tsx

`https://api.geolonia.com/{stage}/embed` has been deprecated.

Use cdn.geolonia.com for JS API

---

src/components/Data/GeoJson.tsx
src/components/Data/GeoJson/hooks/use-geojson.ts
src/components/Data/GeoJsonMeta.tsx

GeoJsonMeta に `allowedOrigins` を保存するフォームを追加しました。
気になる点
- `src/components/Data/GeoJson/hooks/use-geojson.ts` でGeoJSONMetaを取得した際、値が保存されているかどうかを`typeof json.allowedOrigins === "string"` でチェックしていましたが、保存されていない場合は ` undefined` が帰ってきたので`typeof json.allowedOrigins !== "undefined"`に変更しました。
-  https://github.com/geolonia/app.geolonia.com/blob/9657cd12ee6e82b26fcaf995ef1ec1bd70d6497c/src/components/Data/GeoJson/hooks/use-geojson.ts#L47
- public/private のボタンが disabled になっていましたが、AllowedOriginsフォームの表示・非表示のテストのために削除しています。
- https://github.com/geolonia/app.geolonia.com/pull/363/files#diff-f1464bcef7ac9bffa8c7d62645291a21286f314b2d0ca749751bf0f033fa7bd5L200

Add origin auth form

---

.env.development.sample
src/components/Data/GeoJson.tsx
src/components/Data/GeoJson/hooks/use-geojson.ts
src/components/Data/ImportDropZone.tsx
src/components/Data/ImportDropZoneButton.tsx
src/components/Data/MapEditor.tsx
src/components/custom/GeoloniaMap.tsx

Closes #351 
カスタムタイル生成後にダッシュボードで地図を表示する機能を実装しました。
実装内容
- 1秒ごとにポーリングして、`"gvp_status": "created"` 時に`data-simple-vector` にタイルのURLを指定。
- タイルの生成失敗時のメッセージ追加

Draw map after polling

---

src/components/Data/GeoJsons.tsx
src/components/Data/ImportDropZone.tsx
src/components/Data/MapEditor.tsx
src/components/custom/AddNew.tsx

#348 
* GeoJSON作成にエンターを押すと作成できるように
* アップロード時にファイルサイズリミットを正しく（以前は有料チームでも1MBと表示されていた）
* customtiles tiles.jsonのリクエストを統一（sources loaded のイベントを拾って zoom to bounds するように変更）
* トークンが valid じゃない時は、トークンを更新してから地図を読み込む
* GeoJSON作成後一覧に戻る挙動から、新規作成されたGeoJSONの詳細にページ遷移する
* もろもろリファクタリング

Dashboard fixes

---

src/components/Data/GeoJsonMeta.tsx
src/components/Maps/APIKey.tsx

Closes #353 
HTML コードを生成する機能を追加しました。
~~### 相談したい箇所~~
~~get-geolonia が カスタムデータ属性での指定が必要だったので、material-ui の Button コンポーネントから button 要素に変更して実装しました。もっと良い実装があれば教えてもらえればと…！~~
~~https://github.com/geolonia/app.geolonia.com/blob/add-html-template/src/components/Data/GeoJsonMeta.tsx#L428-L439~~

Add html template

---

src/components/Data/GeoJson.tsx
src/components/Data/ImportDropZone.tsx

- GeoJSON コンポーネントのリファクタ
- コールバック関数には useCallback を使う
- props の変数展開の一貫性を改善
- GVP 失敗時は再度 DropZone を表示
close #385

GVP 失敗した時は、エラー表示で再度アップロードを許可

---

src/components/Data/GeoJson.tsx
src/components/Data/GeoJsonMeta.tsx

Closes #388 
変更内容
- 名前、地図ステータス（public/private ・draft/published）、AllowedOrigins の順番に変更（情報のレイヤーとしては名前が優先だと思ったので上に移動しました。どうでしょうか？）
- タイトル下の説明をベクトルタイルの変更に合わせて修正。

UIのレイアウトを変更

---

src/components/Navigator.tsx

Closes #412 
サイドバーの「公式ドキュメント」に target="_blank" を追加しました。
気になる点
target="_blank" 以外の rel 属性が空になり rel となってしまうので、もし他に何か良い方法があれば教えて頂けると…！

サイドバーの「公式ドキュメント」に target="_blank" を追加

---

src/components/Dashboard.tsx
src/components/Navigator.tsx

Closes #419 
ウェルカムカード？の文章を目的別に変更しました。開発者ドキュメントへのリンクも追加したのですがどうでしょうか？
それと、サイドバーのドキュメントへのリンク名の「公式ドキュメント」をより、具体的な「開発者ドキュメント」に変更しました。

ウェルカムカードの文章を目的別に変更

---

src/components/User/avatar.tsx

左上のアイコンに合わせて1:1 で画像中央を表示するようにしました。

Fix user avatar crop

---

src/components/Data/GeoJsonMeta.scss
src/components/Data/GeoJsonMeta.tsx

Closes https://github.com/geolonia/get-geolonia/issues/24
get-geolonia が「Do you have an API key ?」というリンクを追加していたので非表示に。
get-geolonia の方で対応しようかとしたのですが、app.geolonia.com に固有の問題だったのでこちらで修正しました。

get-geolonia の不要なリンクを非表示に

---

src/components/Header.tsx

Closes #430 
右上のロゴをクリック時に外部へ飛ぶとユーザーに違和感を与えそう。（FacebookのロゴをクリックするとFacebookのコーポレートサイトに飛ぶような）なので削除しました。
今後、Geolonia ロゴを押すとホームへ戻る仕様のロゴを追加するのは良さそうです。

Geolonia ロゴの削除

---

src/components/Team/Billing/Receipts.tsx

JPYを使うことにしているので `/100` が不要になりました
Closes #445

Don't divide by 100 when showing JPY

---

.env.development
src/index.tsx

debug とか test とかのオプションが色々あったけど、両方設定しても送信されていたのでapi-dev環境用のtokenをデフォルトで埋め込みました。

Move mixpanel token to .env.development

---

src/lang/ja.json
src/lang/ja.po
src/lang/lang.pot

Closes #483 
少し長いかなと思って文章を削ってみました。どうでしょうか…？（でも原案でも良い様な気もしつつ。。）

ダッシュボード左下のGeoJSON API説明文言 修正

---

src/components/Team/Billing.tsx
src/lang/ja.json
src/lang/ja.po
src/lang/lang.pot
src/lib/billing-tooltip.ts

Close #556 
APIキー毎の合計表示回数をラベルに追加しました。
ラベルに合計表示回数を追加すると、ツールチップにも合計表示回数を表示してしまったため、カスタムツールチップを作成する事で解決しました。

APIキー毎の合計表示回数をラベルに追加

---

src/lib/cognito/parse-error.ts

コードが一致しなかったときのCognitoのエラーがハンドリングできていなかったので修正しました。
close #568

パスワードリセットの時に検証コードのエラーハンドリングを行う

---

src/components/Team/Billing.tsx
src/lang/ja.json
src/lang/ja.po
src/lang/lang.pot

- 地図ロードの `回` の i18nize
- 地図ロードの回数のカンマ桁区切りの追加
- `MM/DD` の日付は `M/D` に変更（`請求対象期間 9/1 ~ 10/1`のような表記の場合はこちらの方が日付を弁別しやすいものと思います）

支払いページの数字フォーマットの修正

---

src/components/Navigator.scss

Fix #338 
あまり綺麗な解決方法とは思えないですが..
もっといい方法ありましたら教えていただけますと 🙇

チーム表示のデザイン崩れを修正

---

.github/workflows/node.js.yml

この変更で、次のプルリクエストからバンドルサイズの変更がCIのビルドログに出力されるようになります。
Close #561

ビルド成果をキャッシュしてバンドルサイズを表示する

---

src/App.scss
src/components/Header.scss
src/components/Navigator.tsx
src/components/Tutorials.tsx
src/components/custom/Title.scss
src/index.scss
src/index.tsx
src/variables.scss
src/variables.ts

- バーの色をメインのオレンジに変更
- この色は CSS と JavaScript の両方で複数箇所で使っているので変数として括り出し
- #576 で設定したアクティブなメニューの色もこの色を採用
変更前:
変更後:

Fix bar color and refactor

---

src/components/Team/Billing/payment-method-modal.tsx
src/components/Team/Billing/plan-modal.tsx

支払い関係のダイアログは、CSS を直書きしていたため一貫性のないスタイルになっていました。
Material UI のコンポーネントを使ってスタイルを他のダイアログ・モーダルと統一。
close #508
|変更前|変更後|
|:--|:--|
|<img width="703" alt="スクリーンショット 2021-09-14 14 03 21" src="https://user-images.githubusercontent.com/6292312/133199916-19c58efa-ef8b-4b39-b380-6e0b7da5db05.png">|<img width="759" alt="スクリーンショット 2021-09-14 14 20 49" src="https://user-images.githubusercontent.com/6292312/133199939-f0e025a0-9f41-4e23-84fd-5b7e2de59d88.png">|
|<img width="803" alt="スクリーンショット 2021-09-14 14 21 53" src="https://user-images.githubusercontent.com/6292312/133199958-a9ce7eff-4cee-437b-bfa4-add9432d612c.png">|<img width="724" alt="スクリーンショット 2021-09-14 14 25 09" src="https://user-images.githubusercontent.com/6292312/133199972-a5e5ccba-a1dc-4231-b719-0aebce78686e.png">|

支払い関係のダイアログのスタイル調整

---

src/components/custom/Delete.tsx
src/lang/ja.json
src/lang/ja.po
src/lang/lang.pot

Fix deletion confirmation text field label

---

src/components/Maps/APIKeys.tsx

意図せず am/pm 表記になっていたため、これを24時間に修正

API キー一覧の時刻フォーマットのバグ修正

---

bin/compare.js

プルリクエストの時にレポートしているバンドルサイズについて、 .map のサイズはあまり気にしなくていいと思うので、除外するようにしました。

Eliminate .map from bundle size report

---

bin/compare.js
package.json
src/components/Header.tsx
src/components/Navigator.scss
src/components/Navigator.tsx
src/components/Paperbase.tsx
src/components/Team/general/delete.tsx
src/components/Team/members/invite.tsx
src/redux/hooks.ts
yarn.lock

- チーム関連の修正
- 削除すると再度チームを選択し直してデータを Fetch するので、その間はチームを選べないように修正
- エラーハンドリング追加
- className プロパティで複数のクラスをくっつけるときは classnames ライブラリを使うように　
- CI の問題: しばらく develop ブランチに更新がないとキャッシュが消えてバンドルサイズのレポートができなくなっていた。しょうがないのでキャッシュがないときはレポートしないように修正

チーム削除のUI改善

---

src/components/custom/languages.tsx
src/lib/signup-referrer.ts

Close #668 
サインアップのクエリ文字列が `&referrer=geolonia.com` だと入力する時にタイポしやすいというフィードバックが合ったので、`&ref=geolonia.com` に変更しました。

Fix signup param key

---

.github/workflows/node.js.yml

Dependabot のプルリクエストではコメントをポストする step が失敗するため

Ignore dependabot in steps which requires authority

---

src/components/Team/Billing/usage-chart.tsx

バーチャートの最後の1日が欠けているので、漏れないように変更。
なお、1ヶ月間として 10/5 - 11/4 の期間を表示したいので、サーバー側で 1日減らす処理をこちらで追加してます。
https://github.com/geolonia/api.app.geolonia.com/pull/242

Fix chart billing period

---

src/components/Team/Billing.tsx
src/components/Team/Billing/usage-chart.tsx
src/constants.ts
src/global.d.ts
src/lang/ja.json
src/lang/ja.po
src/lang/lang.pot
src/redux/actions/team-member.ts

- 地図ロード数制限なしの場合は ∞ を表示
- ボタンの位置修正(前月・次月ボタンが内側に入り込んでいたので直した)
- Operator ロールでも「今月の利用状況」セクションを表示
- チャートの判例を ChartJS のキャンバスから HTML に作り直して合計を表示し、かつコピペできるようにした

支払いページ改修 (#693)

---

src/components/Team/Billing/payment-history.tsx
src/global.d.ts
src/lang/ja.json
src/lang/ja.po

- API からは支払い日のデータを受け取り (geolonia/api.app.geolonia.com/pull/247)、それを請求書の日付としてリストに表示
- 返金の時は金額に取り消し線

Billing page fix
